### ISSUE TITLE
unable to install by pip

### ISSUE THREAD

**Issue by AndCycle** [steveherrin/SpookyOTP#8]
$ ./runtime/bin/pip install https://github.com/steveherrin/SpookyOTP/tarball/1.0.0
Downloading/unpacking https://github.com/steveherrin/SpookyOTP/tarball/1.0.0
  Downloading 1.0.0
  Running setup.py egg_info for package from https://github.com/steveherrin/SpookyOTP/tarball/1.0.0
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-HjO79v-build/setup.py", line 8, in <module>
        version = get_version()
      File "version.py", line 12, in get_version
        raise RuntimeError("No PKG-INFO or .git available "
    RuntimeError: No PKG-INFO or .git available to determine version.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-HjO79v-build/setup.py", line 8, in <module>

```
version = get_version()
```

  File "version.py", line 12, in get_version

```
raise RuntimeError("No PKG-INFO or .git available "
```

RuntimeError: No PKG-INFO or .git available to determine version.

---

Command python setup.py egg_info failed with error code 1 in /tmp/pip-HjO79v-build
Storing complete log in /home/ec2-user/.pip/pip.log

**Comment by AndCycle** [comment]
incorrect issue cause by mixed py ver.
